from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import pandas as pd

from common import PROJECT_ROOT, write_json


def find_metadata_path(path: Path) -> Path | None:
    named = path.with_name(path.stem.replace("_model", "") + "_metadata.json")
    if named.exists():
        return named
    meta = path.parent / "meta.json"
    if meta.exists():
        return meta
    expert_metadata = sorted(path.parent.glob("*_metadata.json"))
    return expert_metadata[0] if expert_metadata else None


def read_metric_score(metadata_path: Path | None) -> tuple[float, float | None, float | None]:
    if metadata_path is None:
        return 0.50, None, None
    try:
        payload = json.loads(metadata_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return 0.55, None, None
    metrics = payload.get("metrics", {})
    f1_macro = metrics.get("f1_macro")
    accuracy = metrics.get("accuracy")
    if isinstance(f1_macro, (int, float)):
        return max(float(f1_macro), 0.05), float(f1_macro), float(accuracy) if isinstance(accuracy, (int, float)) else None
    if isinstance(accuracy, (int, float)):
        return max(float(accuracy) * 0.60, 0.05), None, float(accuracy)
    return 0.55, None, None


def collect_model_candidates(*roots: Path) -> pd.DataFrame:
    rows = []
    for root in roots:
        if not root.exists():
            continue
        for path in sorted(root.rglob("*.pkl")):
            if path.name.lower() in {"scaler.pkl", "preprocessor.pkl"}:
                continue
            size = path.stat().st_size
            meta = find_metadata_path(path)
            score, f1_macro, accuracy = read_metric_score(meta)
            rows.append(
                {
                    "model_path": str(path),
                    "root": str(root),
                    "relative_path": str(path.relative_to(root)),
                    "size_bytes": size,
                    "metadata_path": str(meta) if meta else "",
                    "has_metrics": f1_macro is not None or accuracy is not None,
                    "f1_macro": f1_macro,
                    "accuracy": accuracy,
                    "initial_weight": score,
                }
            )
    return pd.DataFrame(rows)


def calibrated_members_from_report(path: Path) -> list[dict[str, Any]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    members = []
    for row in payload.get("weights", []):
        model_path = row.get("model_path")
        if not model_path:
            continue
        weight = float(row.get("calibrated_weight", 0.0) or 0.0)
        members.append(
            {
                "model_path": model_path,
                "metadata_path": row.get("metadata_path", ""),
                "weight": weight,
                "role": "calibrated_directional" if weight > 0 else row.get("role", "disabled"),
                "expert": row.get("expert", ""),
                "mode": row.get("mode", "NORMAL"),
                "calibration": {
                    "score": float(row.get("calibration_score", 0.0) or 0.0),
                    "trades": int(row.get("trades", 0) or 0),
                    "winrate": float(row.get("winrate", 0.0) or 0.0),
                    "avg_net_return": float(row.get("avg_net_return", 0.0) or 0.0),
                    "total_return": float(row.get("total_return", 0.0) or 0.0),
                    "sharpe_like": float(row.get("sharpe_like", 0.0) or 0.0),
                    "max_drawdown": float(row.get("max_drawdown", 0.0) or 0.0),
                },
            }
        )
    total = sum(member["weight"] for member in members)
    if total > 0:
        for member in members:
            member["weight"] = float(member["weight"] / total)
    return members


def main() -> None:
    parser = argparse.ArgumentParser(description="Create a Fusion ensemble preset from available trained/legacy models.")
    parser.add_argument("--models-root", default=str(PROJECT_ROOT / "models"))
    parser.add_argument("--output", default=str(PROJECT_ROOT / "models" / "fusion_ensemble" / "ensemble_config.json"))
    parser.add_argument("--top-n", type=int, default=50)
    parser.add_argument("--calibration-report", help="calibrated_weights.json generated by backtest_fusion_experts.py")
    args = parser.parse_args()

    if args.calibration_report:
        report_path = Path(args.calibration_report)
        members = calibrated_members_from_report(report_path)
        if not members:
            raise SystemExit(f"No calibrated members found in {report_path}")
        config = {
            "mode": "fusion_ensemble_preset",
            "selection": "backtest_calibrated_expert_weights",
            "calibration_report": str(report_path),
            "members": members,
            "decision": {
                "regime_weighting": True,
                "adaptive_threshold": True,
                "risk_gate": True,
                "min_confidence": 0.55,
            },
        }
        output = write_json(args.output, config)
        csv_path = output.with_suffix(".candidates.csv")
        pd.DataFrame(members).to_csv(csv_path, index=False)
        print(f"ensemble: {output}")
        print(f"candidates: {csv_path}")
        return

    models_root = Path(args.models_root)
    candidates = collect_model_candidates(models_root)
    if candidates.empty:
        raise SystemExit(f"No model candidates found under {models_root}")
    ranked = candidates.sort_values(
        ["has_metrics", "initial_weight", "size_bytes", "relative_path"],
        ascending=[False, False, False, True],
    ).head(args.top_n)
    total = float(ranked["initial_weight"].sum()) or 1.0
    members = []
    for _, row in ranked.iterrows():
        members.append(
            {
                "model_path": row["model_path"],
                "metadata_path": row["metadata_path"],
                "weight": float(row["initial_weight"] / total),
                "role": "metric_ranked" if row["has_metrics"] else "candidate",
            }
        )
    config = {
        "mode": "fusion_ensemble_preset",
        "selection": "metric_ranked_then_largest_candidates",
        "members": members,
        "decision": {
            "regime_weighting": True,
            "adaptive_threshold": True,
            "risk_gate": True,
            "min_confidence": 0.55,
        },
    }
    output = write_json(args.output, config)
    csv_path = output.with_suffix(".candidates.csv")
    ranked.to_csv(csv_path, index=False)
    print(f"ensemble: {output}")
    print(f"candidates: {csv_path}")


if __name__ == "__main__":
    main()
